# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

shallow_clone: true
clone_folder: c:\gopath\src\github.com\theodesp\blockingqueues

init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

# environment variables
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.8

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get ./...
  - go get -u gopkg.in/check.v1
  - go get -u github.com/fortytw2/leaktest

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go vet ./...
  - go test -cpu=2 -race -v ./...

test: off
deploy: off